# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, 0x00000001
    li x28, 0x00000010
    li x27, 0x7FFFFFFF
    li x26, 0x12345678
    li x25, 7
    li x24, 31

    # Basic SLLs
    sll x1, x31, x31       # 0 << 0 → 0
    sll x2, x30, x31       # 1 << 0 → 1
    sll x3, x30, x30       # 1 << 1 → 2
    sll x4, x29, x30       # 1 << 1 → 2
    sll x5, x29, x25       # 1 << 7 → 0x00000080
    sll x6, x29, x24       # 1 << 31 → 0x80000000
    sll x7, x26, x25       # 0x12345678 << 7 = 0x1A2B3C00

    # Register overlap
    sll x8, x28, x28       # 0x10 << 0x10 = 0x00100000
    sll x9, x27, x30       # 0x7FFFFFFF << 1 = 0xFFFFFFFE
    sll x10, x30, x30      # 1 << 1 → 2
    li x11, 2
    sll x11, x11, x11      # 2 << 2 → 8

    # Zero register interactions
    sll x12, x0, x30       # 0 << 1 → 0
    sll x13, x30, x0       # 1 << 0 → 1
    sll x14, x0, x0        # 0 << 0 → 0
    sll x0, x30, x30       # write to x0 (ignored)

    # End
    ecall
    nop
    nop
    nop
