# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000001       # small pos
    li x30, 0xF0000000       # negative (sign bit set)
    li x29, 0xFFFFFFFF       # -1
    li x28, 0xAAAAAAAA       # negative alternating
    li x27, 0x55555555       # positive alternating
    li x26, 0x12345678       # general value
    li x25, 0x80000000       # MSB only (sign bit 1)

    # SRAI tests
    srai x1, x31, 0              # 1 >> 0 = 1
    srai x2, x31, 1              # 1 >> 1 = 0
    srai x3, x30, 4              # 0xF0000000 >> 4 = 0xFF000000
    srai x4, x29, 1              # -1 >> 1 = -1
    srai x5, x28, 1              # 0xAAAAAAAA >> 1 = 0xD5555555
    srai x6, x27, 1              # 0x55555555 >> 1 = 0x2AAAAAAA
    srai x7, x25, 31             # 0x80000000 >> 31 = 0xFFFFFFFF
    srai x8, x0, 5               # 0 >> 5 = 0
    srai x9, x26, 4              # 0x12345678 >> 4 = 0x01234567
    srai x10, x26, 8             # 0x12345678 >> 8 = 0x00123456
    srai x11, x26, 12            # 0x12345678 >> 12 = 0x00012345
    srai x12, x26, 28            # 0x12345678 >> 28 = 0x00000001
    srai x13, x26, 31            # 0x12345678 >> 31 = 0x00000000

    # rd == rs1
    li x14, -32
    srai x14, x14, 5             # -32 >> 5 = -1

    # write to x0 (ignored)
    srai x0, x31, 4              # ignored
    srai x0, x0, 0               # ignored

    # End program
    ecall
    nop
    nop
    nop
