# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, -1                 # 0xFFFFFFFF
    li x28, 0x80000000
    li x27, 0x7FFFFFFF
    li x26, 0x12345678
    li x25, 1
    li x24, 4
    li x23, 31
    li x22, 32
    li x21, 33
    li x20, 63

    # Basic SRAs
    sra x1, x31, x31           # 0 >> 0 → 0
    sra x2, x30, x31           # 1 >> 0 → 1
    sra x3, x29, x30           # -1 >> 1 → -1
    sra x4, x28, x30           # 0x80000000 >> 1 → 0xC0000000
    sra x5, x26, x24           # 0x12345678 >> 4 → 0x01234567
    sra x6, x27, x25           # 0x7FFFFFFF >> 1 → 0x3FFFFFFF
    sra x7, x28, x23           # 0x80000000 >> 31 → 0xFFFFFFFF

    # Masked shifts (rs2 > 31)
    sra x8, x26, x22           # 32 → 0 → unchanged
    sra x9, x26, x21           # 33 → 1
    sra x10, x26, x20          # 63 → 31

    # Register overlap
    sra x11, x30, x30          # 1 >> 1 → 0
    li x12, 0xF0000002
    sra x12, x12, x12          # 0xF0000002 >> 2 → 0xFC000000

    # Zero register interactions
    sra x13, x0, x30           # 0 >> 1 → 0
    sra x14, x30, x0           # 1 >> 0 → 1
    sra x15, x0, x0            # 0 >> 0 → 0
    sra x0, x28, x25           # write to x0 → ignored

    # End
    ecall
    nop
    nop
    nop
