# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, -1
    li x28, 2
    li x27, 0x7FFFFFFF
    li x26, 0x80000000
    li x25, -123
    li x24, 100

    # Basic subtractions
    sub x1, x31, x31         # 0 - 0 → 0
    sub x2, x30, x30         # 1 - 1 → 0
    sub x3, x30, x29         # 1 - (-1) → 2
    sub x4, x29, x30         # -1 - 1 → -2
    sub x5, x27, x29         # 0x7FFFFFFF - (-1) → 0x80000000
    sub x6, x26, x30         # 0x80000000 - 1 → 0x7FFFFFFF
    sub x7, x29, x29         # -1 - (-1) → 0

    # Register overlap
    sub x8, x28, x28         # 2 - 2 → 0
    sub x9, x25, x25         # -123 - (-123) → 0
    sub x10, x24, x24        # 100 - 100 → 0
    li x11, 1
    sub x11, x11, x11        # 1 - 1 → 0

    # Zero register interactions
    sub x12, x0, x30         # 0 - 1 → -1
    sub x13, x30, x0         # 1 - 0 → 1
    sub x14, x0, x0          # 0 - 0 → 0
    sub x0, x30, x30         # write to x0 (ignored)

    # End
    ecall
    nop
    nop
    nop
