# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, -1
    li x28, 0xAAAAAAAA
    li x27, 0x55555555
    li x26, 0x12345678
    li x25, 0x87654321

    # Basic ORs
    or x1, x31, x31         # 0 | 0 → 0
    or x2, x30, x30         # 1 | 1 → 1
    or x3, x30, x31         # 1 | 0 → 1
    or x4, x30, x29         # 1 | -1 → -1
    or x5, x28, x27         # AAAAAAAA | 55555555 → FFFFFFFF
    or x6, x29, x30         # -1 | 1 → -1
    or x7, x26, x25         # 12345678 | 87654321 → 97755779

    # Register overlap
    or x8, x27, x27         # 55555555 | 55555555 → 55555555
    or x9, x29, x29         # -1 | -1 → -1
    or x10, x30, x30        # 1 | 1 → 1
    li x11, 7
    or x11, x11, x11        # 7 | 7 → 7

    # Zero register interactions
    or x12, x0, x30         # 0 | 1 → 1
    or x13, x30, x0         # 1 | 0 → 1
    or x14, x0, x0          # 0 | 0 → 0
    or x0, x30, x30         # write to x0 (ignored)

    # End
    ecall
    nop
    nop
    nop
