# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000000       # Zero
    li x30, 0x00000001       # Small positive
    li x29, 0x7FFFFFFF       # Max positive
    li x28, 0xFFFFFFFF       # -1
    li x27, 0x80000000       # Min negative

    # ADDI tests
    addi x1, x31, 0           # 0 + 0 = 0
    addi x2, x30, 0           # 1 + 0 = 1
    addi x3, x30, 1           # 1 + 1 = 2
    addi x4, x30, -1          # 1 - 1 = 0
    addi x5, x28, 1           # -1 + 1 = 0
    addi x6, x28, -1          # -1 - 1 = -2
    addi x7, x29, 1           # 0x7FFFFFFF + 1 = 0x80000000
    addi x8, x27, -1          # 0x80000000 - 1 = 0x7FFFFFFF
    addi x9, x0, 2047         # Max 12-bit immediate
    addi x10, x0, -2048       # Min 12-bit immediate
    addi x11, x0, 123         # 0 + 123 = 123
    addi x12, x0, -123        # 0 - 123 = -123
    addi x0, x30, 5           # write to x0 → ignored
    addi x0, x0, 0            # rd == rs1 == x0 → ignored

    # rd == rs1 cases
    li x13, 5
    addi x13, x13, 7          # x13 = 5 + 7 = 12

    li x14, -8
    addi x14, x14, -4         # x14 = -8 - 4 = -12

    # End program
    ecall
