# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000001       # 1
    li x30, 0xF0000000       # MSBs set
    li x29, 0xFFFFFFFF       # all ones
    li x28, 0xAAAAAAAA       # alternating 1010...
    li x27, 0x55555555       # alternating 0101...
    li x26, 0x12345678       # general pattern
    li x25, 0x80000000       # MSB only

    # SRLI tests
    srli x1, x31, 0              # 1 >> 0 = 1
    srli x2, x31, 1              # 1 >> 1 = 0
    srli x3, x30, 4              # 0xF0000000 >> 4 = 0x0F000000
    srli x4, x29, 1              # 0xFFFFFFFF >> 1 = 0x7FFFFFFF
    srli x5, x28, 1              # 0xAAAAAAAA >> 1 = 0x55555555
    srli x6, x27, 1              # 0x55555555 >> 1 = 0x2AAAAAAA
    srli x7, x25, 31             # 0x80000000 >> 31 = 0x00000001
    srli x8, x0, 5               # 0 >> 5 = 0
    srli x9, x26, 4              # 0x12345678 >> 4 = 0x01234567
    srli x10, x26, 8             # 0x12345678 >> 8 = 0x00123456
    srli x11, x26, 12            # 0x12345678 >> 12 = 0x00012345
    srli x12, x26, 28            # 0x12345678 >> 28 = 0x00000001
    srli x13, x26, 31            # 0x12345678 >> 31 = 0x00000000

    # rd == rs1
    li x14, 0x00000020
    srli x14, x14, 5             # 0x20 >> 5 = 1

    # write to x0 (ignored)
    srli x0, x31, 4              # ignored
    srli x0, x0, 0               # ignored

    # End program
    ecall
    nop
    nop
    nop
