# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup base registers
    li x31, 0
    li x30, 2
    li x29, 4
    li x28, 6
    li x27, 20
    li x26, 1022
    li x25, -20
    li x24, 1024
    li x23, 2048
    li x22, -1025

    # Basic loads
    lh x1, 0(x31)     # → 0x0000
    lh x2, 0(x30)     # → 0x7FFF
    lh x3, 0(x29)     # → 0x8000 → -32768
    lh x4, 0(x28)     # → 0xFFFF → -1
    lh x5, 0(x27)     # → 0x1234
    lh x6, 0(x26)     # → 0xABCD

    # Offset addressing
    lh x7, 20(x25)    # base = -20 + 20 → addr 0 → 0x0000

    # Register overlap
    li x8, 2
    lh x8, 2(x8)      # addr 4 → 0x8000 → -32768

    # Zero register base
    lh x9, 6(x0)      # → 0xFFFF → -1

    # x0 as destination
    lh x0, 4(x0)      # → 0x8000 → ignored

    # Extreme immediates
    lh x10, -2(x24)       # 1024 - 2 = 1022 → 0xABCD
    lh x11, -2048(x23)    # 2048 - 2048 = 0 → 0x0000
    lh x12, 2047(x22)     # -1025 + 2047 = 1022 → 0xABCD

    # End
    ecall
    nop
    nop
    nop
