# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000000       # zero
    li x30, 0x00000001       # 1
    li x29, 0xFFFFFFFF       # -1
    li x28, 0xAAAAAAAA       # 101010...
    li x27, 0x55555555       # 010101...

    # ORI tests
    ori x1, x31, 0              # 0 | 0 = 0
    ori x2, x30, 0              # 1 | 0 = 1
    ori x3, x30, -1             # 1 | -1 = 0xFFFFFFFF
    ori x4, x29, 0              # -1 | 0 = -1
    ori x5, x29, -1             # -1 | -1 = -1
    ori x6, x28, 0x555          # 0xAAAAAAAA | 0x555 = 0xAAAAAFFF
    ori x7, x27, -1365          # 0x55555555 | 0xFFFFFAAB = 0xFFFFFFFF
    ori x8, x0, 0x123           # 0 | 0x123 = 0x00000123
    ori x9, x0, -2048           # 0 | -2048 = 0xFFFFF800
    ori x10, x0, 2047           # 0 | 2047 = 0x000007FF
    ori x11, x0, -1             # 0 | -1 = 0xFFFFFFFF
    ori x0, x30, 0x7FF          # write to x0 → ignored

    # rd == rs1
    li x12, 0x0F0F0F0F
    ori x12, x12, -256          # 0x0F0F0F0F | 0xFFFFFF00 = 0xFFFFFF0F

    li x13, 0x00000000
    ori x13, x13, 0x7FF         # 0x00000000 | 0x000007FF = 0x000007FF

    li x14, 0xAAAAAAAA
    ori x14, x14, 0x7FF         # 0xAAAAAAAA | 0x7FF = 0xAAAAAFFF

    li x15, 0xF000F000
    ori x15, x15, -2048         # 0xF000F000 | 0xFFFFF800 = 0xFFFFF800

    # End program
    ecall
