# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000001       # 1
    li x30, 0x00000000       # 0
    li x29, 0xFFFFFFFF       # -1
    li x28, 0x7FFFFFFF       # max positive
    li x27, 0x80000000       # min negative

    # SLTI tests
    slti x1, x31, 2              # 1 < 2 → 1
    slti x2, x31, 1              # 1 < 1 → 0
    slti x3, x31, 0              # 1 < 0 → 0
    slti x4, x30, 0              # 0 < 0 → 0
    slti x5, x30, 1              # 0 < 1 → 1
    slti x6, x29, 0              # -1 < 0 → 1
    slti x7, x29, -1             # -1 < -1 → 0
    slti x8, x29, -2             # -1 < -2 → 0
    slti x9, x28, -1             # 0x7FFFFFFF < -1 → 0
    slti x10, x27, 1             # 0x80000000 < 1 → 1
    slti x11, x0, 1              # 0 < 1 → 1
    slti x12, x0, -1             # 0 < -1 → 0
    slti x0, x31, 1              # write to x0 → ignored

    # rd == rs1
    li x13, -1
    slti x13, x13, 0             # -1 < 0 → 1

    # Max/min immediates
    slti x14, x30, 2047          # 0 < 2047 → 1
    slti x15, x30, -2048         # 0 < -2048 → 0

    # End program
    ecall
