# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0                  # 0
    li x30, 1                  # 1
    li x29, -1                 # 0xFFFFFFFF (unsigned: large)
    li x28, 123
    li x27, 456
    li x26, -123               # 0xFFFFFF85
    li x25, -456               # 0xFFFFFE38
    li x24, 0x7FFFFFFF         # signed max
    li x23, 0x80000000         # signed min (but unsigned > signed max)

    # Unsigned comparisons
    sltu x1, x28, x27          # 123 < 456 → 1
    sltu x2, x28, x28          # equal → 0
    sltu x3, x29, x31          # 0xFFFFFFFF < 0 → 0
    sltu x4, x31, x29          # 0 < 0xFFFFFFFF → 1
    sltu x5, x26, x27          # 0xFFFFFF85 < 456 → 0
    sltu x6, x27, x26          # 456 < 0xFFFFFF85 → 1
    sltu x7, x25, x26          # 0xFFFFFE38 < 0xFFFFFF85 → 1
    sltu x8, x24, x23          # 0x7FFFFFFF < 0x80000000 → 1
    sltu x9, x23, x24          # 0x80000000 < 0x7FFFFFFF → 0

    # Register overlap
    sltu x10, x27, x27         # rs1 == rs2 → 0

    li x11, 0
    sltu x11, x27, x11         # rs2 == rd → 456 < 0 → 0

    li x12, 0
    sltu x12, x12, x27         # rs1 == rd → 0 < 456 → 1

    li x13, 456
    sltu x13, x13, x26         # rs1 == rd → 456 < 0xFFFFFF85 → 1

    li x14, 0xFFFFFFFF
    sltu x14, x14, x14         # full overlap → 0

    # Zero register interactions
    sltu x15, x0, x30          # 0 < 1 → 1
    sltu x16, x30, x0          # 1 < 0 → 0
    sltu x17, x0, x0           # 0 < 0 → 0
    sltu x0, x30, x30          # write to x0 → ignored

    # End
    ecall
