# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup base registers
    li x31, 0
    li x30, 2
    li x29, 4
    li x28, 6
    li x27, 20
    li x26, 1022
    li x25, -20
    li x24, 1024
    li x23, 2048
    li x22, -2048
    li x21, 0       # base for +1022 offset

    # Basic loads
    lhu x1, 0(x31)     # → 0x0000
    lhu x2, 0(x30)     # → 0x7FFF
    lhu x3, 0(x29)     # → 0x8000
    lhu x4, 0(x28)     # → 0xFFFF
    lhu x5, 0(x27)     # → 0x1234
    lhu x6, 0(x26)     # → 0xABCD

    # Offset addressing
    lhu x7, 20(x25)    # -20 + 20 = 0 → 0x0000

    # Register overlap
    li x8, 2
    lhu x8, 2(x8)      # addr = 4 → 0x8000

    # Zero register base
    lhu x9, 6(x0)      # → 0xFFFF

    # x0 as destination
    lhu x0, 4(x0)      # → 0x8000 → ignored

    # Extreme immediates
    lhu x10, -2(x24)      # 1024 - 2 = 1022 → 0xABCD
    lhu x11, -2048(x23)   # 2048 - 2048 = 0 → 0x0000
    lhu x12, 1022(x21)    # 0 + 1022 = 1022 → 0xABCD

    # End
    ecall
