# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0                  # 0
    li x30, 1                  # +1
    li x29, -1                 # -1 (0xFFFFFFFF)
    li x28, 123                # small positive
    li x27, 123                # same as x28
    li x26, -123               # small negative
    li x25, 456
    li x24, -456
    li x23, 0x7FFFFFFF         # INT_MAX
    li x22, 0x80000000         # INT_MIN

    # Signed comparisons
    slt x1, x28, x25           # 123 < 456 → 1
    slt x2, x28, x27           # 123 < 123 → 0
    slt x3, x26, x28           # -123 < 123 → 1
    slt x4, x28, x26           # 123 < -123 → 0
    slt x5, x24, x26           # -456 < -123 → 1
    slt x6, x26, x24           # -123 < -456 → 0
    slt x7, x22, x23           # INT_MIN < INT_MAX → 1
    slt x8, x23, x22           # INT_MAX < INT_MIN → 0

    # Partial register overlap
    slt x13, x25, x25          # rs1 == rs2 → 0

    li x14, 0
    slt x14, x25, x14          # rs2 == rd → 456 < 0 → 0

    li x15, 0
    slt x15, x15, x25          # rs1 == rd → 0 < 456 → 1

    li x16, -456
    slt x16, x25, x16          # rd == rs2 → 456 < -456 → 0

    li x17, 456
    slt x17, x17, x26          # rd == rs1 → 456 < -123 → 0

    # Full register overlap
    li x9, -1
    slt x9, x9, x9             # -1 < -1 → 0

    # Zero register interactions
    slt x10, x0, x30           # 0 < 1 → 1
    slt x11, x30, x0           # 1 < 0 → 0
    slt x12, x0, x0            # 0 < 0 → 0
    slt x0, x30, x30           # write to x0 → ignored

    # End
    ecall
