# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup base registers
    li x31, 0
    li x30, 4
    li x29, 8
    li x28, 12
    li x27, 1020
    li x26, -4
    li x25, 1024

    # Basic loads
    lw x1, 0(x31)     # → 0x00000000
    lw x2, 0(x30)     # → 0x12345678
    lw x3, 0(x29)     # → 0xFFFFFFFF
    lw x4, 0(x28)     # → 0x80000000
    lw x5, 0(x27)     # → 0x89ABCDEF

    # Offset access
    lw x6, 4(x26)     # -4 + 4 = 0 → 0x00000000

    # Register overlap
    li x7, 4
    lw x7, 0(x7)      # addr = 4 → 0x12345678

    # Zero register base
    lw x8, 8(x0)      # → 0xFFFFFFFF

    # x0 as destination
    lw x0, 12(x0)     # → 0x80000000 → ignored

    # Extreme immediates
    lw x9, -4(x25)      # 1024 - 4 = 1020 → 0x89ABCDEF
    li x10, -1024
    lw x10, 2044(x10)   # -1024 + 2044 = 1020 → 0x89ABCDEF

    # End
    ecall
