# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000001       # 1
    li x30, 0x0000000F       # 15
    li x29, 0x0000FFFF       # 16-bit ones
    li x28, 0x80000001       # MSB and LSB set
    li x27, 0xFFFFFFFF       # all ones
    li x26, 0x12345678
    li x25, 0x00000000

    # SLLI tests
    slli x1, x31, 0              # 1 << 0 = 1
    slli x2, x31, 1              # 1 << 1 = 2
    slli x3, x31, 4              # 1 << 4 = 16
    slli x4, x30, 2              # 15 << 2 = 60
    slli x5, x29, 8              # 0x0000FFFF << 8 = 0x00FFFF00
    slli x6, x28, 1              # 0x80000001 << 1 = 0x00000002
    slli x7, x27, 31             # 0xFFFFFFFF << 31 = 0x80000000
    slli x8, x0, 5               # 0 << 5 = 0
    slli x9, x26, 8              # 0x12345678 << 8 = 0x34567800
    slli x10, x26, 12            # 0x12345678 << 12 = 0x45678000
    slli x11, x26, 28            # 0x12345678 << 28 = 0x80000000
    slli x12, x26, 31            # 0x12345678 << 31 = 0x00000000

    # rd == rs1
    li x13, 0x00000001
    slli x13, x13, 5             # 1 << 5 = 32

    # Edge shamt
    li x14, 0xAAAAAAAA
    slli x14, x14, 31            # LSB shifted into MSB: 0x00000000

    # Writes to x0 (must be ignored)
    slli x0, x31, 4              # ignored
    slli x0, x0, 0               # ignored (rd == rs1 == x0)

    # End program
    ecall
    nop
    nop
    nop
