# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, 0x80000000
    li x28, 0x12345678
    li x27, 7
    li x26, 31
    li x25, 32
    li x24, 33
    li x23, 63

    # Basic SRLs
    srl x1, x31, x31       # 0 >> 0 → 0
    srl x2, x30, x31       # 1 >> 0 → 1
    srl x3, x29, x30       # 0x80000000 >> 1 → 0x40000000
    srl x4, x28, x27       # 0x12345678 >> 7 → 0x002468acf
    srl x5, x28, x26       # 0x12345678 >> 31 → 0x0

    # Masked shifts (rs2 > 31)
    srl x11, x28, x25      # 32 → 0 → unchanged
    srl x12, x28, x24      # 33 → 1
    srl x13, x28, x23      # 63 → 31

    # Register overlap
    srl x6, x30, x30       # 1 >> 1 → 0
    li x7, 2
    srl x7, x7, x7         # 2 >> 2 → 0

    # Zero register interactions
    srl x8, x0, x30        # 0 >> 1 → 0
    srl x9, x30, x0        # 1 >> 0 → 1
    srl x10, x0, x0        # 0 >> 0 → 0
    srl x0, x30, x30       # write to x0 (ignored)

    # End
    ecall
    nop
    nop
    nop
