# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0x00000001           # +1
    li x30, 0x00000000           # 0
    li x29, 0xFFFFFFFF           # max unsigned
    li x28, 0x7FFFFFFF           # max signed
    li x27, 0x80000000           # MSB set

    # Unsigned comparisons
    sltiu x1, x30, 0             # 0 < 0 → 0
    sltiu x2, x30, 1             # 0 < 1 → 1
    sltiu x3, x31, 1             # 1 < 1 → 0
    sltiu x4, x31, 2             # 1 < 2 → 1
    sltiu x5, x31, 0             # 1 < 0 → 0
    sltiu x6, x30, 2047          # 0 < 2047 → 1
    sltiu x7, x31, 2047          # 1 < 2047 → 1
    sltiu x8, x28, 2047          # 0x7FFFFFFF < 2047 → 0
    sltiu x9, x27, 2047          # 0x80000000 < 2047 → 0
    sltiu x10, x29, 2047         # 0xFFFFFFFF < 2047 → 0
    sltiu x11, x30, -2048        # 0 < 0xFFFFF800 → 1
    sltiu x12, x29, -2048        # 0xFFFFFFFF < 0xFFFFF800 → 0

    # x0 interactions
    sltiu x13, x0, 1             # 0 < 1 → 1
    sltiu x14, x0, -2048         # 0 < 0xFFFFF800 → 1
    sltiu x15, x0, 0             # 0 < 0 → 0
    sltiu x0, x31, 1             # rd = x0 (ignored)
    sltiu x0, x0, 0              # rd = rs1 = x0 (ignored)

    # End
    ecall
