# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, -1
    li x28, 2
    li x27, 0x7FFFFFFF
    li x26, 0x80000000
    li x25, -123
    li x24, 100

    # Basic additions
    add x1, x31, x31         # 0 + 0 → 0
    add x2, x30, x30         # 1 + 1 → 2
    add x3, x30, x29         # 1 + -1 → 0
    add x4, x29, x29         # -1 + -1 → -2
    add x5, x27, x30         # 0x7FFFFFFF + 1 → 0x80000000
    add x6, x26, x29         # 0x80000000 + -1 → 0x7FFFFFFF
    add x7, x29, x30         # -1 + 1 → 0

    # Register overlap
    add x8, x28, x28         # 2 + 2 → 4
    add x9, x25, x25         # -123 + -123 → -246
    add x10, x24, x24        # 100 + 100 → 200
    li x11, 1
    add x11, x11, x11        # 1 + 1 → 2

    # Zero register interactions
    add x12, x0, x30         # 0 + 1 → 1
    add x13, x30, x0         # 1 + 0 → 1
    add x14, x0, x0          # 0 + 0 → 0
    add x0, x30, x30         # write to x0 (ignored)

    # End
    ecall
