# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup
    li x31, 0
    li x30, 1
    li x29, -1
    li x28, 0xAAAAAAAA
    li x27, 0x55555555
    li x26, 0xFFFFFFFF
    li x25, 0x12345678
    li x24, 0x87654321

    # Basic XORs
    xor x1, x31, x31         # 0 ^ 0 → 0
    xor x2, x30, x30         # 1 ^ 1 → 0
    xor x3, x30, x31         # 1 ^ 0 → 1
    xor x4, x30, x29         # 1 ^ -1 → -2
    xor x5, x28, x27         # AAAAAAAA ^ 55555555 → FFFFFFFF
    xor x6, x26, x30         # FFFFFFFF ^ 1 → FFFFFFFE
    xor x7, x25, x24         # 12345678 ^ 87654321

    # Register overlap
    xor x8, x27, x27         # 55555555 ^ 55555555 → 0
    xor x9, x29, x29         # -1 ^ -1 → 0
    xor x10, x30, x30        # 1 ^ 1 → 0
    li x11, 0xFFFFFFFF
    xor x11, x11, x11        # FFFFFFFF ^ FFFFFFFF → 0

    # Zero register interactions
    xor x12, x0, x30         # 0 ^ 1 → 1
    xor x13, x30, x0         # 1 ^ 0 → 1
    xor x14, x0, x0          # 0 ^ 0 → 0
    xor x0, x30, x30         # write to x0 (ignored)

    # End
    ecall
    nop
    nop
    nop
