# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup using temp regs
    li x31, 0x00000000       # zero
    li x30, 0x00000001       # 1
    li x29, 0xFFFFFFFF       # -1
    li x28, 0xAAAAAAAA       # 101010...
    li x27, 0x55555555       # 010101...

    # XORI tests
    xori x1, x31, 0            # 0 ^ 0 = 0
    xori x2, x30, 0            # 1 ^ 0 = 1
    xori x3, x30, -1           # 1 ^ -1 = 0xFFFFFFFE
    xori x4, x29, 0            # -1 ^ 0 = -1
    xori x5, x29, -1           # -1 ^ -1 = 0
    xori x6, x28, 0x555        # 0xAAAAAAAA ^ 0x00000555 = 0xAAAAAFFF
    xori x7, x27, -1365        # 0x55555555 ^ 0xFFFFFAAB = 0xAAAAAFFE
    xori x8, x0, 0x123         # 0 ^ 0x123 = 0x00000123
    xori x9, x0, -2048         # 0 ^ -2048 = 0xFFFFF800
    xori x10, x0, 2047         # 0 ^ 2047 = 0x000007FF
    xori x11, x0, -1           # 0 ^ -1 = 0xFFFFFFFF
    xori x0, x30, 0x7FF        # write to x0 → ignored

    # rd == rs1
    li x12, 0x0F0F0F0F
    xori x12, x12, -256        # = 0x0F0F0F0F ^ 0xFFFFFF00 = 0xF0F0F00F

    li x13, 0xFFFFFFFF
    xori x13, x13, -409        # = 0xFFFFFFFF ^ 0xFFFFFE67 = 0x00000198

    # End program
    ecall
