# Auto-generated by ChatGPT
.section .text
.global _start
_start:

    # Setup base registers
    li x31, 0
    li x30, 1
    li x29, 2
    li x28, 3
    li x27, 10
    li x26, 1023
    li x25, -10
    li x24, 1024
    li x23, 2048
    li x22, 0      # base for +1023 offset

    # Basic loads
    lbu x1, 0(x31)     # → 0x00
    lbu x2, 0(x30)     # → 0x7F
    lbu x3, 0(x29)     # → 0x80
    lbu x4, 0(x28)     # → 0xFF
    lbu x5, 0(x27)     # → 0x55
    lbu x6, 0(x26)     # → 0xAA

    # Offset addressing
    lbu x7, 10(x25)    # -10 + 10 = 0 → 0x00

    # Register overlap
    li x8, 2
    lbu x8, 1(x8)      # addr = 3 → 0xFF

    # Zero register base
    lbu x9, 2(x0)      # → 0x80

    # x0 as destination
    lbu x0, 1(x0)      # → 0x7F → ignored

    # Extreme immediates
    lbu x10, 1023(x0)     # → 0xAA
    lbu x11, -1(x24)      # 1024 - 1 = 1023 → 0xAA
    lbu x12, -2048(x23)   # 2048 - 2048 = 0 → 0x00
    lbu x13, 1023(x22)    # 0 + 1023 = 1023 → 0xAA

    # End
    ecall
